name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1

      - uses: pre-commit/action@v3.0.0
